baseURL = 'https://nextmountainoverland.com/'
languageCode = 'en-us'
title = 'Next Mountain Overland'
theme = 'PaperMod'

# Enable emoji support
enableEmoji = true

# Enable RSS
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Pagination
paginate = 10

# PaperMod specific settings
[params]
  description = "Mark and Valarie's journey from RV adventures to the Pan American Highway on motorcycles"
  author = "Mark & Valarie"
  
  # Show reading time and word count
  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  
  # Date format
  DateFormat = "January 2, 2006"
  
  # Enable search
  ShowSearchPage = true
  
  # Images
  images = ["/images/nextmtn-social.jpg"]
  
  # Home page settings
  [params.homeInfoParams]
    Title = "Next Mountain Overland"
    Content = """
Welcome to our journey! We're Mark and Valarie, early retirees exploring North America in our F-550 RV (NextMtn) 
while preparing for our 2027 adventure: riding motorcycles from Colorado to Argentina on the Pan American Highway.

Follow along as we document our travels, preparations, and the lessons we learn along the way.
"""

  # Social links
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/nextmountainoverland"
  
  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30
  
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Markup settings for better content rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = false

# Privacy settings (respecting open web principles)
[privacy]
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    simple = true
  [privacy.youtube]
    privacyEnhanced = true
